name: release
on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@561b19deda1228a0edf856c3325df87416f8c9bd # v2.0.0
        with:
          generate_attestations: true
          go_version_file: go.mod
          release_tag: ${{ inputs.ref || github.ref }}

